language: java
branches:
  only:
    - master
env:
  - GOPATH=$HOME/go PATH=$GOPATH/bin:$PATH
before_script:
  - npm install -g codeclimate-test-reporter
  - go get -u github.com/jpmonette/apexcov
script:
  - git submodule add --force https://github.com/florianhoehn/seamless.git
  - ant -lib seamless/lib/ -f seamless/build.xml build
  - apexcov
  - codeclimate-test-reporter ./coverage/lcov.info
notifications:
  slack: mavenschat:2Pmhpn10xoK1ZfvHfV648YHe